baseURL = 'https://wooworks.github.io/'
languageCode = 'en-us'
defaultContentLanguage = 'ko'
title = 'wooworks'
theme = 'coder'

[params]
  description = "인디메이커의 일과 삶, 생각들을 기록합니다."
  author = "wooworks"
  keywords = ["wooworks", "blog", "인디메이커", "인디해커"]
  hideColorSchemeToggle = true
  images = ["/images/wooworks_opengraph.png"] # Open Graph 이미지 경로
  faviconSVG = "/images/wooworks-favicon-32.svg"
  favicon_32 = "/images/wooworks-favicon-32.png"
  favicon_16 = "/images/wooworks-favicon-16.png"
  touchicon  = "/images/my-touch-icon.png"

[menu]
  [[menu.main]]
    name = "about"
    url = "/about/"
    weight = 1

  [[menu.main]]
    name = "project"
    url = "/project/"
    weight = 2 

  [[menu.main]]
    name = "note"
    url = "/posts/"
    weight = 3

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
